---
# include variables
- name: Tuned: Include OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "main.yml"
  tags: tuned

# install package
- name: Tuned - Manage the tuned packages
  package: name={{ tuned_package_name }} state={{ tuned_package_state }}
  tags: tuned

# manage main configuration files
- name: Tuned - Manage tuned-main.conf
  template: src=../templates/tuned-main.conf.j2 dest="{{ tuned_config_dir }}/tuned-conf"
  notify: tuned_service_restart
  tags: tuned

# manage service
- name: Tuned - Manage tuned service
  service: name={{ tuned_service_name }} state={{ tuned_service_state }}
  tags: tuned
